################### Monitoring finance config  ###############################
#                                                                            #
#     Author : Manouchehr Rasouli                                            #
#                                                                            #
##############################################################################

# The finance config file created define new credits and financial configuration for each one

free:
  url_activities:
    up_check: yes
    email_on_down: yes
    tracking: yes
    check_time_slot: 10 #10 Min
  url_check_locations:
    - zanjan
  credit_time: infinit # Day
  maximum_url: 5
  price: free # rial

